- name: Misc packages
  become: true
  become_user: "{{ devpc__superuser }}"
  block:
    - name: Install misc packages
      apt:
        name:
          - curl
          - tree
          - meld

    - name: Install Slack
      snap:
        name: slack
        classic: yes
