user_favorite_apps__desktop_files: "['google-chrome.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Nautilus.desktop', 'code.desktop', 'slack_slack.desktop', 'virt-manager.desktop', 'show-desktop.desktop']"
