- name: unattended-upgrades
  become: true
  become_user: "{{ devpc__superuser }}"
  block:
    - name: Uninstall unattended-upgrades
      apt:
        name: unattended-upgrades
        state: absent
