- name: user
  become: true
  become_user: "{{ devpc__superuser }}"
  block:
    - name: Create group
      group:
        name: "{{ item.name }}"
        gid: "{{ item.gid | default(omit) }}"
      loop: "{{ system_group__groups | default([]) }}"
